POST http://localhost:5001/api/auth/register
Content-Type: application/json

{
    "firstName":"Le",
    "lastName":"hung",
    "email":"tinhyeucuatui2002@gmail.com",
    "password":"hung12345"
}

#####
//login
POST   http://localhost:5001/api/auth/login
Content-Type: application/json

{
    "email":"tinhyeucuatui2002@gmail.com",
    "password":"hung12345"
}

###
//load user
POST http://localhost:5001/api/auth/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWJmZjAzNzVkY2MxOTZjMGNlNzRlMTMiLCJpYXQiOjE2Mzk5Njg4MzV9.oORqFg_wc4XO3sLD1q1logrIvz6xfYYRsMkEraWVcEY


######
//Product post test

POST   http://localhost:5001/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWJmZjAzNzVkY2MxOTZjMGNlNzRlMTMiLCJpYXQiOjE2NDAyMjU5ODR9.J2HjS886h-A1E6D6iTBZ8FUFCwETPuN61AQkqe120oo
Content-Type: application/json 

{
    "name":"iPhone 7",
    "category":"Smartphone",
    "description":"Apple iphone 7",
    "imageUrl":"https://24hstore.vn/images/products/2020/04/19/large/iphone-7-rose-gold.jpg",
    "color":["Black","Rose","Gold"],
    "skus":[
        {
            "size":"32GB",
            "price":"399"
        },
        {
            "size":"128GB",
            "price":"699"
        }
    ],
    "quantity":101,
    "brand":"Apple"
}

##########
GET  http://localhost:5001/api/products


######
GET http://localhost:5001/api/products/myproducts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWJmZjAzNzVkY2MxOTZjMGNlNzRlMTMiLCJpYXQiOjE2NDAyMjU5ODR9.J2HjS886h-A1E6D6iTBZ8FUFCwETPuN61AQkqe120oo 

##########
PUT http://localhost:5001/api/products/61c3d9d6be83e6caeb84d1bb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWJmZjAzNzVkY2MxOTZjMGNlNzRlMTMiLCJpYXQiOjE2NDAyMjU5ODR9.J2HjS886h-A1E6D6iTBZ8FUFCwETPuN61AQkqe120oo
Content-Type: application/json

{
    "name": "iPhone SE 2020"
}


################################################################
DELETE  http://localhost:5001/api/products/61c3d9d5be83e6caeb84d1b7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWJmZjAzNzVkY2MxOTZjMGNlNzRlMTMiLCJpYXQiOjE2NDAyMjU5ODR9.J2HjS886h-A1E6D6iTBZ8FUFCwETPuN61AQkqe120oo